workflows:
  android-debug:
    name: Voice Recorder Debug APK
    environment:
      java: 17
    scripts:
      - ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
