workflows:
  android-debug:
    name: Voice Recorder Debug APK
    environment:
      java: 17
    scripts:
      - chmod +x ./gradlew
      - ./gradlew clean
      - ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/debug/*.apk
